FROM tengelisconsulting/ez_worker_base:latest
RUN apk add --update --no-cache \
        build-base \
        python3-dev \
        && python3 -m pip install mypy \
        && apk del \
        build-base \
        python3-dev
